/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudang;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Customer
 */
public class KategoriBarang extends javax.swing.JFrame {

    /**
     * Creates new form KategoriBarang
     */
    public KategoriBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new gudang.Background();
        BahanRumahTangga = new javax.swing.JButton();
        Perabot = new javax.swing.JButton();
        BahanMasakan = new javax.swing.JButton();
        Rokok = new javax.swing.JButton();
        Lain = new javax.swing.JButton();
        Kembali = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Makanan = new javax.swing.JButton();
        Minuman = new javax.swing.JButton();
        Obat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BahanRumahTangga.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BahanRumahTangga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-dispenser-32.png"))); // NOI18N
        BahanRumahTangga.setText("Bahan Rumah Tangga");
        BahanRumahTangga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahanRumahTanggaActionPerformed(evt);
            }
        });

        Perabot.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Perabot.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-duster-32.png"))); // NOI18N
        Perabot.setText("Peralatan Rumah Tangga");
        Perabot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerabotActionPerformed(evt);
            }
        });

        BahanMasakan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BahanMasakan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-ingredients-32.png"))); // NOI18N
        BahanMasakan.setText("Bahan Masakan");
        BahanMasakan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BahanMasakanActionPerformed(evt);
            }
        });

        Rokok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Rokok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-smoking-32.png"))); // NOI18N
        Rokok.setText("Rokok");
        Rokok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RokokActionPerformed(evt);
            }
        });

        Lain.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Lain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-question-mark-32.png"))); // NOI18N
        Lain.setText("Lain-Lain");
        Lain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LainActionPerformed(evt);
            }
        });

        Kembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Kembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-back-to-32.png"))); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pilih Kategori barang");

        Makanan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Makanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-food-32.png"))); // NOI18N
        Makanan.setText("Makanan");
        Makanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MakananActionPerformed(evt);
            }
        });

        Minuman.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Minuman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-energy-sport-drink-32.png"))); // NOI18N
        Minuman.setText("Minuman");
        Minuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinumanActionPerformed(evt);
            }
        });

        Obat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Obat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-alternative-herbal-medicine-32 (1).png"))); // NOI18N
        Obat.setText("Obat-Obatan");
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Makanan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Minuman)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Lain))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BahanMasakan, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BahanRumahTangga, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Obat)
                            .addComponent(Perabot)))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Rokok, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Kembali, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Makanan)
                    .addComponent(Minuman)
                    .addComponent(Lain))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BahanMasakan)
                    .addComponent(Obat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BahanRumahTangga)
                    .addComponent(Perabot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Rokok)
                .addGap(18, 18, 18)
                .addComponent(Kembali)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MakananActionPerformed
        this.dispose();
        try {
            new gudang.Makanan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MakananActionPerformed

    private void MinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinumanActionPerformed
        this.dispose();
        try {
            new gudang.Minuman().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MinumanActionPerformed

    private void LainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LainActionPerformed
        this.dispose();
        try {
            new gudang.Lain().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_LainActionPerformed

    private void BahanMasakanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahanMasakanActionPerformed
        this.dispose();
        try {
            new gudang.BahanMasakan().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BahanMasakanActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
        this.dispose();
        try {
            new gudang.Obat().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ObatActionPerformed

    private void BahanRumahTanggaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BahanRumahTanggaActionPerformed
        this.dispose();
        try {
            new gudang.BahanRumah().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BahanRumahTanggaActionPerformed

    private void PerabotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerabotActionPerformed
        this.dispose();
        try {
            new gudang.Perabot().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_PerabotActionPerformed

    private void RokokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RokokActionPerformed
        this.dispose();
        try {
            new gudang.Rokok().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(KategoriBarang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_RokokActionPerformed

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        this.dispose();
        new gudang.Menu().setVisible(true);
    }//GEN-LAST:event_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KategoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KategoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KategoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KategoriBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KategoriBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BahanMasakan;
    private javax.swing.JButton BahanRumahTangga;
    private javax.swing.JButton Kembali;
    private javax.swing.JButton Lain;
    private javax.swing.JButton Makanan;
    private javax.swing.JButton Minuman;
    private javax.swing.JButton Obat;
    private javax.swing.JButton Perabot;
    private javax.swing.JButton Rokok;
    private gudang.Background background1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
