/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gudang;

/**
 *
 * @author Customer
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background1 = new gudang.Background();
        UbahAdmin = new javax.swing.JButton();
        HapusAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DaftarBarang = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UbahAdmin.setBackground(new java.awt.Color(255, 255, 255));
        UbahAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        UbahAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-32.png"))); // NOI18N
        UbahAdmin.setText("Edit Admin");
        UbahAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UbahAdminActionPerformed(evt);
            }
        });

        HapusAdmin.setBackground(new java.awt.Color(255, 255, 255));
        HapusAdmin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        HapusAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-32.png"))); // NOI18N
        HapusAdmin.setText("Hapus Admin");
        HapusAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusAdminActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu Gudang");

        DaftarBarang.setBackground(new java.awt.Color(255, 255, 255));
        DaftarBarang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DaftarBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-list-32.png"))); // NOI18N
        DaftarBarang.setText("Kategori Barang");
        DaftarBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DaftarBarangActionPerformed(evt);
            }
        });

        Logout.setBackground(new java.awt.Color(255, 255, 255));
        Logout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logout-32.png"))); // NOI18N
        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout background1Layout = new javax.swing.GroupLayout(background1);
        background1.setLayout(background1Layout);
        background1Layout.setHorizontalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(UbahAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(HapusAdmin)
                .addGap(37, 37, 37))
            .addGroup(background1Layout.createSequentialGroup()
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Logout))
                    .addGroup(background1Layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(DaftarBarang)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        background1Layout.setVerticalGroup(
            background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(background1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(DaftarBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(background1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UbahAdmin)
                    .addComponent(HapusAdmin))
                .addGap(18, 18, 18)
                .addComponent(Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UbahAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UbahAdminActionPerformed
        this.dispose();
        new gudang.UbahAdmin().setVisible(true);
    }//GEN-LAST:event_UbahAdminActionPerformed

    private void HapusAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusAdminActionPerformed
        this.dispose();
        new gudang.HapusAdmin().setVisible(true);
    }//GEN-LAST:event_HapusAdminActionPerformed

    private void DaftarBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DaftarBarangActionPerformed
        this.dispose();
        new gudang.KategoriBarang().setVisible(true);
    }//GEN-LAST:event_DaftarBarangActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        this.dispose();
        new gudang.FormLogin().setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DaftarBarang;
    private javax.swing.JButton HapusAdmin;
    private javax.swing.JButton Logout;
    private javax.swing.JButton UbahAdmin;
    private gudang.Background background1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
